### PR TITLE
Improved look for the website

### PR DESCRIPTION
**Pull request by aviks**
I thought BinaryBuilder deserved a slightly better designed website. Plus the expanse of red hurt my eyes. 

The primary change is in typography.  Using Oswald and Quattrocento fonts. Reduce the red. Get rid of materilize css framework, and use pure-css, a simpler and smaller alternative. Move some content from layout template to content page. 

Before and after images below. 

image

### CODE REVIEW

**Comment by aviks** [comment]
I've fixed some minor alignment issues, and converted the images to svg.

**Comment by aviks** [comment]
Merge?

**Comment by giordano** [comment]
Yeah, let's see how it goes :slightly_smiling_face:   Thanks!

**Comment by giordano** [comment]
@aviks it looks great, except that on my computer the icons overlap with the titles.  Any idea of how to fix this?  I can reproduce with both Firefox and Chrome

Screenshot_20200628_004939

**Comment by aviks** [comment]
That is not nice, ouch. You're on Linux, right?  What's your screen resolution? Physical and logical? I've tested this primarily on Firefox on Windows, where it looks all right, but the bottom margin of those images are clearly dodgy.

**Comment by giordano** [comment]
Yes, Linux, screen resolution 2880x1880 (scaled down to 2304x1440)

**Comment by aviks** [comment]
>  2880x1880 (scaled down to 2304x1440)

That's a very odd scaling factor 😕

**Comment by giordano** [comment]
Also with full resolution I see the same effect

**Comment by aviks** [comment]
> Also with full resolution I see the same effect

Yeah, of course. My comment above was very tangential.

**Comment by aviks** [comment]
Should be a fix in #9 ... I hope... 🤞

**Pull request merged**
